### ISSUE TITLE
"Discard Only On Success" not behaving as the name suggests

### ISSUE THREAD

**Issue by abhishek-choudhury-callhub** [jenkinsci/enhanced-old-build-discarder-plugin#10]
### Describe your use-case which is not covered by existing documentation.

I want to delete logs only if the build succeeds and to hold onto failed logs. I've used the following settings in the GUI for Enhanced Log Rotator:

1. Days to keep builds: 1
2. Max # of builds to keep: 10
3. Discard Only On Success: checked
4. Hold Max Builds: unchecked

I would highly appreciate any insights on why this is happening.

**Comment by abhishek-choudhury-callhub** [comment]
@MarkEWaite, I've noticed that you have merged the latest PR. Can you guide me on where I might find help?

**Comment by MarkEWaite** [comment]
> @MarkEWaite, I've noticed that you have merged the latest PR. Can you guide me on where I might find help?

Your request seems to be a request for help, not a report of an issue or improvement.

Please use the [community forum](https://community.jenkins.io/), the [mailing lists](https://www.jenkins.io/mailing-lists/), and the [chat channels](https://www.jenkins.io/chat/) for questions.

When you use the issue tracker to ask a question, you narrow the number of people that will see your question and increase the chances that your question will not be answered.  When you ask your question in a wider forum, others may offer answers that meet your need without requiring a specific plugin.

I'm not a user of this plugin nor am I an active maintainer of this plugin.

**Comment by abhishek-choudhury-callhub** [comment]
Thanks, @MarkEWaite. I wasn't aware there were community channels. I'm closing the request.

**Comment by abhishek-choudhury-callhub** [comment]
@BenjaminBeggs, I noticed you are the maintainer of the plugin. I've asked my [question](https://community.jenkins.io/t/enhanced-old-build-discarders-discard-only-on-success-not-behaving-as-the-name-suggests/3489) in the [community forum](https://community.jenkins.io/), but I've not received an answer yet.

I would highly appreciate it if you could help me with it. I'm using Jenkins 2.346.3 and Version: 1.4 of Enhanced Old Build Discarder. The plugin was working for me in Jenkins 2.251.

**Comment by BenjaminBeggs** [comment]
Hi there, thanks for messaging me about this. I am not actively maintaining this plugin and am unsure why newer Jenkins versions would have broken this feature. Sorry I can’t help out more. I don’t have access to my development environment for this project anymore to look into this.

If another developer wants to try and fix this issue I am happy to work with them in making sure they have the needed repository privileges to make their commits.

Aug 24, 2022, 05:05 by ***@***.***:
